### ISSUE TITLE
name more explicitly 

### ISSUE THREAD

**Issue by Lada496** [Lada496/star-wars-list#40]
[nitpick] - It might be better to rename this variable, as `value` is a bit too generic. Other devs might think; _"What kind of value do you mean?"_

_Originally posted by @kei95 in https://github.com/Lada496/star-wars-list/pull/34#discussion_r1113951679_

**Comment by kei95** [comment]
Where did you exactly fix it? I still see the line I commented on in the commit you made; `const value = character[filterFactor]`
